### PR TITLE
Cleanup readme and add Travis CI integration

### PR DESCRIPTION
**Pull request by fancycode**
This PR updates the readme to remove all unnecessary steps, so only the minimal required commands remain. The configuration can now be set through a regular `make XXX_defconfig` target, similar to what we are using for the uboot.

Also Travis CI integration has been added to make sure compilation is not broken by future changes. By using `ccache`, it takes less than 3 minutes for a full rebuild.

@VladimirKhlystov Please review my changes and provide some feedback.
@farindk FYI and please check if the description in the readme is sufficient for building.

Hallo, fancycode,
this is correct (with make spreedboard_v1_defconfig). I have to eincheck 1 file with firmware for Uboot-
gxbb_p200_1G_1Gbit.dtb . Copy this file into dtb.imb in first patition microSD. This file is for Spreebbox V2
Vladimr

### CODE REVIEW

**Comment by fancycode** [comment]
There is a warning when building, this should probably be investigated:
```
WARNING: modpost: Found 7 section mismatch(es).
To see full details build your kernel with:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
```

**Comment by VladimirKhlystov** [comment]
Hallo, fancycode,
this is correct (with make spreedboard_v1_defconfig). I have to eincheck 1 file with firmware for Uboot-
gxbb_p200_1G_1Gbit.dtb . Copy this file into dtb.imb in first patition microSD. This file is for Spreebbox V2

**Comment by fancycode** [comment]
I'm not sure if I understand correctly, but I assume this means the changes are ok ;-) Will merge now.

**Comment by VladimirKhlystov** [comment]
Hi!!! New version linux-kernel-4.9.4 is out in branche Linux-4.9.4 :)

**Pull request merged**
